routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
|--------------------------------------------------------------------------
| Trash , Restore, Permanent Delete
|--------------------------------------------------------------------------
|
| Selalu letakkan 3 controller tersebut di atas resource method
| karena full memakai CRUD resource maka menggunakan ::resource
|
*/

Route::get('/', function(){
    return view('auth.login');
});
 /*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");
Auth::routes();//login

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');
 /*
|--------------------------------------------------------------------------
| USERS
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");//karena full memakai resource

/*
|--------------------------------------------------------------------------
| CATEGORY
|--------------------------------------------------------------------------
*/

 Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');

 Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');

 Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');



Route::resource('/categories', 'CategoryController');
/*
|--------------------------------------------------------------------------
| BOOKS
|--------------------------------------------------------------------------
*/

Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');

Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');

Route::resource('/books', 'BookController');
Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch'); // fitur pencarian buku menggunakan ajax
/*
|--------------------------------------------------------------------------
| ORDERS
|--------------------------------------------------------------------------
*/
Route::resource('orders', 'OrderController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        // OTORISASI GATE
        $this->middleware(function($request, $next)
        {
            if(Gate::allows('manage-users')) return $next($request);
            abort(403, 'Oops!Anda tidak memiliki hak akses kesini');
          });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // get all data with paginate
        $users = User::paginate(10);
        // FILTER
        // ambil request inputtan
        $filterKeyword = $request->get('keyword');
        // cek jika ada $filterKeyword maka kita query User 
        // yang emailnya memiliki sebagian dari keyword 
        $status = $request->get('status');
        if($status)
        {
                $users = User::where('status', $status)->paginate(10);
        } else {
                $users = User::paginate(10);
        }
        if($filterKeyword)
        {
            // kita cari menggunakan model User method where(),dan kita 
            // gunakan operator LIKE dan nilai dari keyword 
            // kita bungkus dalam '%%' sehingga query 
            // akan mencari User yang memiliki 
            // email mengandung keyword tertentu, 
            // bukan exact match
            if($status){
                $users = \App\User::where('email', 'LIKE', "%$filterKeyword%")
                    ->where('status', $status)
                    ->paginate(10);
            } else {
                $users = \App\User::where('email', 'LIKE', "%$filterKeyword%")
                    ->paginate(10);
            }
         }
        // return view to list all user
        return view('users.index',['users' => $users]);
        // untuk test form -> return view("users.create");
        //ini fitur form untuk membuat user
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("users.create");
        //ini fitur form untuk membuat user
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // membuat validation menggunakan facade \Validator dengan method make()
        // Method tersebut menerima 2 parameter, parameter pertama kita isi dengan semua request dari form $request->all() 
        // bertipe array, parameter kedua juga bertipe array, yaitu rules dari masing-masing field yang divalidas
        \Validator::make($request->all(),[
            "name" => "required|min:4|max:70",
            "username" => "required|min:2|max:40",
            "roles" => "required",
            "avatar" => "required",
            "address" => "required|min:8",
            "email" => "required|email",
            "password" => "required|min:8",
            "password_confirmation" => "required|min:8|same:password" 
        ])->validate();
        // setelah membuat validator nya , di view juga dibuat untuk memunculkan tampilan / notif errornya
        $create_user = new User;
        $create_user->username = $request->get('name');
        $create_user->name= $request->get('username');
        $create_user->roles = json_encode($request->get('roles'));
        $create_user->phone = $request->get('phone');
        $create_user->address = $request->get('address');
        $create_user->email = $request->get('email');
        $create_user->password = \Hash::make($request->get('password'));
        // upload file handling
        if($request->file('avatar'))
        // cek apakah request memiliki file dengan nama avatar,
        // jika ada maka simpan file tersebut menggunakan method 
        // $request->file()->store().
        {
            $file = $request->file('avatar')->store('avatars', 'public');
            $create_user->avatar = $file; 
            // Method store() akan menghasilkan path dari file yang kita simpan. 
            // Sehingga kode di atas akan menghasilkan string path di mana lokasi file berada, 
            // kita memerlukan string tersebut untuk disimpan sebagai nilai 'avatar' di kolom tabel users
        }
        $create_user->save();
        // send notif for success adding new user
        return redirect()->route('users.index')->with('status', 'User successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id); //cari ID
        return view('users.detail', ['user' => $user]); //tampilkan 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        //gunakan findOrFail agar jika id user atau user 
        //tidak ditemukan , akan redirect ke page not found, 
        //dan bukan error
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \Validator::make($request->all(),[
            "name" => "required|min:4|max:70",
            "roles" => "required",
            "phone" => "required|digits_between:10,12",
            "address" => "required|min:10"
        ])->validate();
        $user = User::findOrFail($id);

        $user->name = $request->get('name');
        $user->address = $request->get('address');
        $user->roles = json_encode($request->get('roles'));
         // Untuk field roles sebelum menyimpan ke database 
        // kita ubah dulu dari PHP Array menjadi JSON 
        // Array menggunakan fungsi json_encode() 
        // agar dapat disimpan ke database.
        $user->phone = $request->get('phone');
        $user->status = $request->get('status');
        if($request->file('avatar')) 
        // cek apakah ada request bertipe file dengan nama 'avatar'
        {
            // jika ada , kita cek lagi
            if($user->avatar && file_exists(storage_path('app/public/' . $user->avatar)))
            {
                //  apakah user yang akan diedit ini memiliki file avatar 
                // dan apakah file tersebut ada di database, jika ada 
                // maka kita hapus file tersebut
                \Storage::delete('public/'.$user->avatar);
                // Untuk menghapus file kita gunakan \Storage::delete() argument yang 
                // dimasukan adalah path relatif dari storage/app tidak perlu 
                // full path. Maka dari itu kita menggunakan 
                // 'public/'. $user->avatar yang akan menghapus file di 
                // folder storage/app/public/avatars/fileavataruser.png misalnya.
            }
            // Setelah itu kita simpan file yang diupload ke folder "avatars" 
            // seperti sebelumnya menggunakan method store()
            $file = $request->file('avatar')->store('avatars', 'public');
            // Lalu kita set field 'avatar' user dengan path baru dari image 
            // yang diupload tadi
            $user->avatar = $file;
        }
        $user->save();
        //redirect ke form edit user dengan status bahwa berhasil melakukan update
        return redirect()->route('users.index')->with('status', 'User succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('users.index')->with('status', 'User successfully deleted');
    }
}

resources/views/users/create.blade.php
@extends("layouts.global")

@section("title") Tambahkan User Baru @endsection

@section("content")

<div class="col-md-8">
    <!-- notif for successfully adding new user -->
    @if(session('status'))
    <!--nge check apakah ada variable status -->
    <div class="alert alert-success">
        <!-- jika ada akan di tampilan alert -->
        {{session('status')}}
    </div>
    @endif
    <!-- buat form -->
    <!-- kita juga set form attribute enctype bernilai 
        "multipart/form-data" 
        karena kita akan mengunggah (mengupload) file dari form ini. -->
    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('users.store')}}" method="POST">

        @csrf
        <!-- blade helper @csrf ini berfungsi 
        untuk menggenerate token 
        csrf seperti ini: -->
        <!-- 
        <input 
         type="hidden"  
       (
            hidden fungsinya untuk ngecheck bahwa request 
            yang dikirimkan adalah request yang valid. 
       ) 
        name="_token"
        value="HPoyywkM2LR0RMlL4qHfe9TwPAi75IgvXeL9PX4b">
         -->
        <!-- INPUT WITH VALIDATION -->
        <!-- FIELD NAME -->
        <label for="name">Nama</label>
        <!-- 
            1. menampilkan data yang diketik oleh user sebelumnya menggunakan method old('name')
            2. berikan class is-invalid jika terdapat error untuk field name. Untuk mengecek apakah 
               terdapat error kita bisa gunakan $errors->first('name')
            3. Pemberian class "is-invalid" adalah agar input tersebut memiliki border berwarna merah. 
               Ini merupakan styling / class dari template bootstrap yang kita pakai, yaitu polished template.
         -->
        <input value="{{old('name')}}" class="form-control {{$errors->first('name') ? "is-invalid": ""}}"
            placeholder="Full Name" type="text" name="name" id="name" />
        <!-- 4. tampilkan pesan error dari field name -->
        <div class="invalid-feedback">
            {{$errors->first('name')}}
        </div>
        <br>
        <!-- FIELD USERNAME -->
        <label for="username">Username</label>
        <input value="{{old('username')}}" class="form-control {{$errors->first('username') ? "is-invalid" : ""}}"
            placeholder="username" type="text" name="username" id="username" />
        <div class="invalid-feedback">
            {{$errors->first('username')}}
        </div>
        <br>
        <!-- FIELD ROLES -->
        <label for="">Roles</label>
        <br>
        <!-- ADMIN  -->
        <input class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" type="checkbox" name="roles[]"
            id="ADMIN" value="ADMIN">
        <label for="ADMIN">Administrator</label>
        <!-- STAFF -->
        <input class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" type="checkbox" name="roles[]"
            id="STAFF" v alue="STAFF">
        <label for="STAFF">Staff</label>
        <!-- CUSTOMER -->
        <input class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" type="checkbox" name="roles[]"
            id="CUSTOMER" value="CUSTOMER">
        <label for="CUSTOMER">Customer</label>
        <div class="invalid-feedback">
            {{$errors->first('roles')}}
        </div>
        <br>
        <!-- FIELD NOMOR HP -->
        <br>
        <label for="phone">Nomor Hp</label>
        <br>
        <input value="{{old('phone')}}" type="text" name="phone"
            class="form-control {{$errors->first('phone') ? "is-invalid" : ""}} ">
        <div class="invalid-feedback">
            {{$errors->first('phone')}}
        </div>
        <br>
        <!-- FIELD ADDRESS -->
        <label for="address">Alamat</label>
        <textarea name="address" id="address" class="form-control {{$errors->first('address') ? "is-invalid" : ""}}">
            {{old('address')}}
            </textarea>
        <div class="invalid-feedback">
            {{$errors->first('address')}}
        </div>
        <br>
        <!-- FIELD AVATAR -->
        <label for="avatar">Avatar</label>
        <br>
        <input id="avatar" name="avatar" type="file"
            class="form-control {{$errors->first('avatar') ? "is-invalid" : ""}}">
        <div class="invalid-feedback">
            {{$errors->first('avatar')}}
        </div>

        <hr class="my-3">
        <!-- FIELD EMAIL -->
        <label for="email">Email</label>
        <input value="{{old('email')}}" class="form-control {{$errors->first('email') ? "is-invalid" : ""}}"
            placeholder="user@mail.com" type="text" name="email" id="email" />
        <div class="invalid-feedback">
            {{$errors->first('email')}}
        </div>
        <br>
        <!-- FIELD PASSWORD -->
        <label for="password">Password</label>
        <input class="form-control {{$errors->first('password') ? "is-invalid" : ""}}" placeholder="password"
            type="password" name="password" id="password" />
        <div class="invalid-feedback">
            {{$errors->first('password')}}
        </div>
        <br>
        <!-- FIELD PASSWORD CONFIRM -->
        <label for="password_confirmation">Konfirmasi Password</label>
        <input class="form-control {{$errors->first('password_confirmation') ? "is-invalid" : ""}}"
            placeholder="password confirmation" type="password" name="password_confirmation"
            id="password_confirmation" />
        <div class="invalid-feedback">
            {{$errors->first('password_confirmation')}}
        </div>
        <br>

        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
</div>

@endsection

resources/views/users/detail.blade.php
@extends('layouts.global')

@section('title') Detail User @endsection

@section('content')

<div class="col-md-8">
    <div class="card">
        <div class="card-body">
            <b>Name:</b> <br />
            {{$user->name}}
            <br><br>

            @if($user->avatar)
            <img src="{{asset('storage/'. $user->avatar)}}" width="128px" />
            @else
            No avatar
            @endif

            <br>
            <br>
            <b>Username:</b><br>
            {{$user->email}}

            <br>
            <br>
            <b>Phone number</b> <br>
            {{$user->phone}}

            <br><br>
            <b>Address</b> <br>
            {{$user->address}}

            <br>
            <br>
            <b>Roles:</b> <br>
            @foreach (json_decode($user->roles) as $role)
            &middot; {{$role}} <br>
            @endforeach
        </div>
    </div>
</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.global')

@section('title') Edit User @endsection

<!-- buat form -->
@section('content')
<div class="col-md-8">

    @if(session('status'))
    <div class="alert alert-success">
        {{session('status')}}
    </div>
    @endif

    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{route('users.update', [$user->id])}}"
        method="POST">

        @csrf
        <!-- 
            Untuk menggunakan method selain GET dan POST,maka kita 
            harus memberikan nilai method pada form sebagai POST, 
            lalu kita tambahkan input bertipe hidden dengan 
            nama _method bernilai nama method yang akan 
            digunakan. 
            Misalnya untuk mengirim data dengan method PUT kita 
            menggunakan input hidden ini:
            <input name="_method" name="PUT">
            Dan untuk menggunakan method DELETE tinggal kita 
            ganti valuenya menjadi seperti ini:
            <input name="_method" name="DELETE">
         -->
        <!-- INPUT WITH VALIDATION -->
        <input type="hidden" value="PUT" name="_method">
        <!-- NAME -->
        <label for="name">Name</label>
        <label for="name">Name</label>
        <input value="{{old('name') ? old('name') : $user->name}}"
            class="form-control {{$errors->first('name') ? "is-invalid" : ""}}" placeholder="Full Name" type="text"
            name="name" id="name" />
        <div class="invalid-feedback">
            {{$errors->first('name')}}
        </div>
        <br>
        <!-- USERNAME -->
        <!-- agar tidak bisa diubah gunakan disabled -->
        <label for="username">Username</label>
        <input value="{{$user->username}}" disabled class="form-control" placeholder="username" type="text"
            name="username" id="username" />
        <br>
        <!-- FITUR STATUS -->
        <label for="">Status</label>
        <br />
        <input {{$user->status == "ACTIVE" ? "checked" : ""}} value="ACTIVE" type="radio" class="form-control"
            id="active" name="status"> <label for="active">Active</label>
        <input {{$user->status == "INACTIVE" ? "checked" : ""}} value="INACTIVE" type="radio" class="form-control"
            id="inactive" name="status"> <label for="inactive">Inactive</label>
        <br><br>
        <!-- ROLES -->
        <label for="">Roles</label>
        <!-- <br> -->
        <!-- 
            Untuk roles kita akan mencentang input 
            checkbox di tiap-tiap role yang dimiliki user, 
            kita melakukannya bantuan php function in_array()
         -->
        <!-- 
             Kode di atas mengecek apakah $user->roles didalamnya 
             terdapat string "ADMIN". Kita menggunakan json_decode() 
             untuk mengubah dari string JSON Array kembali ke PHP Array.
          -->
        <!-- ADMIN -->
        <br>
        <input type="checkbox" {{in_array("ADMIN", json_decode($user->roles)) ? "checked" : ""}} name="roles[]"
            class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" id="ADMIN" value="ADMIN">
        <label for="ADMIN">Administrator</label>
        <!-- STAFF -->
        <input type="checkbox" {{in_array("STAFF", json_decode($user->roles)) ? "checked" : ""}} name="roles[]"
            class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" id="STAFF" value="STAFF">
        <label for="STAFF">Staff</label>
        <!-- CUSTOMER -->
        <input type="checkbox" {{in_array("CUSTOMER", json_decode($user->roles)) ? "checked" : ""}} name="roles[]"
            class="form-control {{$errors->first('roles') ? "is-invalid" : "" }}" id="CUSTOMER" value="CUSTOMER">
        <label for="CUSTOMER">Customer</label>
        <div class="invalid-feedback">
            {{$errors->first('roles')}}
        </div>
        <br>

        <br>
        <!-- PHONE -->
        <label for="phone">Phone number</label>
        <br>
        <input type="text" name="phone" class="form-control {{$errors->first('phone') ? "is-invalid" : ""}}"
            value="{{old('phone') ? old('phone') : $user->phone}}">
        <div class="invalid-feedback">
            {{$errors->first('phone')}}
        </div>

        <br>
        <!-- ADDRESS -->
        <label for="address">Address</label>
        <textarea name="address" id="address"
            class="form-control {{$errors->first('address') ? "is-invalid" : ""}}">{{old('address') ? old('address') : $user->address}}</textarea>
        <div class="invalid-feedback">
            {{$errors->first('address')}}
        </div>
        <br>
        <!-- AVATAR -->
        <label for="avatar">Avatar image</label>
        <br>
        <!-- AVATAR -->
        <!-- 
            Khusus untuk menampilkan avatar kita lakukan pengecekkan, 
            jika user memiliki avatar kita tampilkan image avatarnya, 
            jika tidak ada avatar kita tampilkan teks "Tidak ada avatar"
         -->
        Current avatar: <br>
        @if($user->avatar)
        <img src="{{asset('storage/'.$user->avatar)}}" width="120px" />
        <br>
        @else
        No avatar
        @endif
        <br>
        <input id="avatar" name="avatar" type="file" class="form-control">
        <!-- 
            keterangan untuk mengabaikan field input ini 
            jika tidak ingin mengubah avatar 
        -->
        <small class="text-muted">Kosongkan jika tidak ingin mengubah avatar</small>

        <hr class="my-3">
        <!-- EMAIL -->
        <label for="email">Email</label>
        <input value="{{$user->email}}" disabled class="form-control {{$errors->first('email') ? "is-invalid" : ""}} "
            placeholder="user@mail.com" type="text" name="email" id="email" />
        <div class="invalid-feedback">
            {{$errors->first('email')}}
        </div>
        <br>
        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
</div>
@endsection

resources/views/users/index.blade.php
@extends("layouts.global")

@section("title") Daftar User @endsection

<!-- @section("content") -->

<!-- gunakan foreach untuk list data user dari variabel
     yang ada di controller -->
@section("content")

<!-- NOTIF -->
@if(session('status'))
<div class="alert alert-success">
    {{session('status')}}
</div>
@endif

<!-- FILTER -->

<form action="{{route('users.index')}}">
    <div class="row">
        <div class="col-md-5">
            <input value="{{Request::get('keyword')}}" name="keyword" class="form-control" type="text"
                placeholder="Masukkan kata kunci.." />
        </div>
        <div class="row">
            <div class="col-md-3">
                <input {{Request::get('status') == 'ACTIVE' ? 'checked' : ''}} value="ACTIVE" name="status" type="radio"
                    class="form-control" id="active">
                <label for="active">Active</label>
            </div>
            <div class="col-md-3">
                <input {{Request::get('status') == 'INACTIVE' ? 'checked' : ''}} value="INACTIVE" name="status"
                    type="radio" class="form-control" id="inactive">
                <label for="inactive">Inactive</label>
            </div>
            <div class="col-md-2">
                <input type="submit" value="Filter" class="btn btn-primary">
            </div>
        </div>


    </div>
</form>

<hr class="my-2">

<!-- meletakkan daftar user pada section content -->
<!-- FITUR CREATE USER -->

<div class="row">
    <div class="col-md-12 text-left">
        <a href="{{route('users.create')}}" class="btn btn-primary btn-sm">+ Tambah user</a>
    </div>
</div>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th><b>Name</b></th>
            <th><b>Username</b></th>
            <th><b>Email</b></th>
            <th><b>Avatar</b></th>
            <th><b>Status</b></th>
            <th><b>Action</b></th>

        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <!-- mengambil berdasarkan row atau data -->
            <!-- NAME -->
            <td>{{$user->name}}</td>
            <!-- USERNAME -->
            <td>{{$user->username}}</td>
            <!-- EMAIL -->
            <td>{{$user->email}}</td>
            <!-- AVATAR -->
            <td>
                <!-- untuk avatar terdapat 2 state
                    1. jika ada avatarnya
                    2. jika tidak ada 
                -->
                @if($user->avatar)
                <img src="{{asset('storage/'.$user->avatar)}}" width="70px" />
                @else
                N/A
                @endif

            </td>
            <!-- STATUS -->
            <td>
                @if($user->status == "ACTIVE")
                <span class="badge badge-success">
                    {{$user->status}}
                </span>
                @else
                <span class="badge badge-danger">
                    {{$user->status}}
                </span>
                @endif
            </td>
            <!-- ACTION -->
            <td>
                <!-- [TODO: actions] -->
                <!-- EDIT -->
                <a class="btn btn-info text-white btn-sm" href="{{route('users.edit', [$user->id])}}">
                    Edit</a>
                <!-- DETAIL -->
                <a href="{{route('users.show', [$user->id])}}" class="btn btn-primary btn-sm">Detail</a>
                <!-- DELETE -->

                <!-- Set validasi apakah benar ingin dihapus -->
                <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline"
                    action="{{route('users.destroy', [$user->id])}}" method="POST">

                    @csrf

                    <input type="hidden" name="_method" value="DELETE">

                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan=10>
                {{$users->appends(Request::all())->links()}}
            </td>
        </tr>
    </tfoot>
</table>

@endsection