routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
|--------------------------------------------------------------------------
| Trash , Restore, Permanent Delete
|--------------------------------------------------------------------------
|
| Selalu letakkan 3 controller tersebut di atas resource method
| karena full memakai CRUD resource maka menggunakan ::resource
|
*/

Route::get('/', function(){
    return view('auth.login');
});
 /*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");
Auth::routes();//login

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');
 /*
|--------------------------------------------------------------------------
| USERS
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");//karena full memakai resource

/*
|--------------------------------------------------------------------------
| CATEGORY
|--------------------------------------------------------------------------
*/

 Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');

 Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');

 Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');



Route::resource('/categories', 'CategoryController');
/*
|--------------------------------------------------------------------------
| BOOKS
|--------------------------------------------------------------------------
*/

Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');

Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');

Route::resource('/books', 'BookController');
Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch'); // fitur pencarian buku menggunakan ajax
/*
|--------------------------------------------------------------------------
| ORDERS
|--------------------------------------------------------------------------
*/
Route::resource('orders', 'OrderController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;
    public function categories()
    {
        return $this->belongsToMany('App\Category');
      }
    public function books()
    {
        return $this->belongsToMany('App\Book')->withPivot('quantity');
        //mengambil field yang berada di tabel pivot yaitu field quantity
    }
    public function orders()
    {
      return $this->belongsToMany('App\Order');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Gate;

class BookController extends Controller
{
    public function __construct()
    {
        // OTORISASI GATE
        $this->middleware(function($request, $next)
        {
            if(Gate::allows('manage-books')) return $next($request);
            abort(403, 'Oops!Anda tidak memiliki hak akses kesini');
          });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // memberikan query param / query string di url seperti ini:

        // http://{url}/books?status=publish

        // Untuk menampilkan buku berstatus PUBLISH

        // http://{url}/books?status=draft

        // Untuk menampilkan buku berstatus DRAFT
        $status = $request->get('status');
        $keyword = $request->get('keyword') ? $request->get('keyword') : '';
    
        if($status){
            $books = \App\Book::with('categories')->where('title', "LIKE", "%$keyword%")->where('status', strtoupper($status))->paginate(10);
        } else {
            $books = \App\Book::with('categories')->where("title", "LIKE", "%$keyword%")->paginate(10);
        }
    
        return view('books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(),[
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ])->validate();
        $books = new Book;
        $books->title = $request->get('title');
        $books->description = $request->get('description');
        $books->author = $request->get('author');
        $books->publisher = $request->get('publisher');
        $books->price = $request->get('price');
        $books->stock = $request->get('stock');

        $books->status = $request->get('save_action');//save_action = tipe button
        // nilainya hanya dua yaitu PUBLISH atau DRAFT sehingga keduanya 
        // sudah sesuai dengan tipe field status pada tabel books

        $cover = $request->file('cover');
        if($cover){
        $cover_path = $cover->store('book-covers', 'public');

        $books->cover = $cover_path;
        }
        $books->slug = \Str::slug($request->get('title'));
        $books->created_by = \Auth::user()->id; 
        $books->save();
        $books->categories()->attach($request->get('categories'));//dapatkan kategori
        // kondisi ketika akan menyimpan
        if($request->get('save_action') == 'PUBLISH')
        {
            // jika ingin di publish akan notifnya seperti ii
            return redirect()->route('books.index')->with('status', 'Book successfully saved and published');
        } else 
        {
            // jika ingin di simpan dulu di draft notifnya seperti ini
            return redirect()->route('books.index')->with('status', 'Book saved as draft');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        return view('books.edit', ['book' => $book]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = Book::findOrFail($id);
        \Validator::make($request->all(),[
            "title" => "required|min:5|max:200",
            "slug" => [
            "required",
                Rule::unique("books")->ignore($book->slug, "slug")
                    ],
            "description" => "required|min:7|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "integer|required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
        ])->validate();

        $book->title = $request->get('title');
        $book->slug = $request->get('slug');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->stock = $request->get('stock');
        $book->price = $request->get('price');

        $new_cover = $request->file('cover');

        if($new_cover){
        if($book->cover && file_exists(storage_path('app/public/' . $book->cover))){
            \Storage::delete('public/'. $book->cover);
        }

        $new_cover_path = $new_cover->store('book-covers', 'public');

        $book->cover = $new_cover_path;
    }

    $book->updated_by = \Auth::user()->id;

    $book->status = $request->get('status');

    $book->categories()->sync($request->get('categories'));

    $book->save();

    return redirect()->route('books.index')->with('status', 'Book successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = \App\Book::findOrFail($id);
        $book->delete();

        return redirect()->route('books.index')->with('status', 'Book moved to trash');
    }
    public function trash()
    {   
        $books = \App\Book::onlyTrashed()->paginate(10);

        return view('books.trash', ['books' => $books]);

    }
    public function restore($id)
    {
        $book = \App\Book::withTrashed()->findOrFail($id);
      
        if($book->trashed()){
          $book->restore();
          return redirect()->route('books.trash')->with('status', 'Book successfully restored');
        } else {
          return redirect()->route('books.trash')->with('status', 'Book is not in trash');
        }
    }
    public function deletePermanent($id)
    {
        $book = \App\Book::withTrashed()->findOrFail($id);
      
        if(!$book->trashed()){
          return redirect()->route('books.trash')->with('status', 'Book is not in trash!')->with('status_type', 'alert');
        } else {
          $book->categories()->detach();
          $book->forceDelete();
      
          return redirect()->route('books.trash')->with('status', 'Book permanently deleted!');
        }
    }
}

resources/views/books/create.blade.php
@extends('layouts.global')

@section('title') Tambah book @endsection

@section('content')
<!-- NOTIF -->
@if(session('status'))
<div class="alert alert-success">
    {{session('status')}}
</div>
@endif
<!-- FORM -->
<div class="row">
    <div class="col-md-8">
        <form action="{{route('books.store')}}" method="POST" enctype="multipart/form-data"
            class="shadow-sm p-3 bg-white">

            @csrf

            <label for="title">Title</label> <br>
            <input value="{{old('title')}}" type="text"
                class="form-control {{$errors->first('title') ? "is-invalid" : ""}} " name="title"
                placeholder="Book title">
            <div class="invalid-feedback">
                {{$errors->first('title')}}
            </div>
            <br>

            <label for="cover">Cover</label>
            <input type="file" class="form-control {{$errors->first('cover') ? "is-invalid" : ""}} " name="cover">
            <div class="invalid-feedback">
                {{$errors->first('cover')}}
            </div>
            <br>

            <label for="description">Description</label><br>
            <textarea name="description" id="description"
                class="form-control {{$errors->first('description') ? "is-invalid" : ""}} "
                placeholder="Give a description about this book">{{old('description')}}</textarea>
            <div class="invalid-feedback">
                {{$errors->first('description')}}
            </div>
            <br>

            <!-- SELECT CATEGORIES -->
            <label for="categories">Categories</label>
            <br>
            <select name="categories[]" multiple id="categories" class="form-control">
            </select>
            <br>
            <br>
            <!-- 

                Input untuk memilih kategori di atas merupakan select karena input tersebut 
                yang akan kita pasangkan dengan plugin select2 kemudian kita beri attribute 
                multiple dan name menggunakan array ([]) seperti ini categories[] karena 
                kita akan mengizinkan lebih dari satu kategori dipilih. Dan kita beri id 
                categories sebagai selector untuk select2.

             -->

            <label for="stock">Stock</label><br>
            <input value="{{old('stock')}}" type="number"
                class="form-control {{$errors->first('stock') ? "is-invalid" : ""}} " id="stock" name="stock" min=0
                value=0>
            <div class="invalid-feedback">
                {{$errors->first('stock')}}
            </div>
            <br>

            <label for="author">Author</label><br>
            <input value="{{old('author')}}" type="text"
                class="form-control {{$errors->first('author') ? "is-invalid" : ""}} " name="author" id="author"
                placeholder="Book author">
            <div class="invalid-feedback">
                {{$errors->first('author')}}
            </div>
            <br>

            <label for="publisher">Publisher</label> <br>
            <input value="{{old('publisher')}}" type="text"
                class="form-control {{$errors->first('publisher') ? "is-invalid" : ""}} " id="publisher"
                name="publisher" placeholder="Book publisher">
            <div class="invalid-feedback">
                {{$errors->first('publisher')}}
            </div>
            <br>

            <label for="Price">Price</label> <br>
            <input value="{{old('price')}}" type="number"
                class="form-control {{$errors->first('price') ? "is-invalid" : ""}} " name="price" id="price"
                placeholder="Book price">
            <div class="invalid-feedback">
                {{$errors->first('price')}}
            </div>
            <br>
            <!-- BUTTON PUBLISH -->
            <!-- untuk langsung release -->
            <button class="btn btn-primary" name="save_action" value="PUBLISH">Publish</button>
            <!-- BUTTON SAVE TO DRAFT -->
            <!-- untuk di simpan sementara -->
            <button class="btn btn-secondary" name="save_action" value="DRAFT">Save as draft</button>
        </form>
    </div>
</div>
@endsection

@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<!--  kode jquery select2 -->
<script>
$('#categories').select2({
    ajax: {
        url: 'http://127.0.0.1:8000/ajax/categories/search',
        processResults: function(data) {
            return {
                results: data.map(function(item) {
                    return {
                        id: item.id,
                        text: item.name
                    }
                })
            }
        }
    }
});
</script>

@endsection

resources/views/books/edit.blade.php
@extends('layouts.global')

@section('title') Edit book @endsection

@section('content')


<div class="row">
    <div class="col-md-8">

        <form enctype="multipart/form-data" method="POST" action="{{route('books.update', [$book->id])}}"
            class="p-3 shadow-sm bg-white">

            @csrf
            <input type="hidden" name="_method" value="PUT">

            <label for="title">Title</label><br>
            <input type="text" class="form-control {{$errors->first('title') ? "is-invalid" : ""}}"
                value="{{old('title') ? old('title') : $book->title}}" name="title" placeholder="Book title" />
            <br>

            <label for="cover">Cover</label><br>
            <small class="text-muted">Current cover</small><br>
            @if($book->cover)
            <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
            @endif
            <br><br>
            <input type="file" class="form-control" name="cover">
            <small class="text-muted">Kosongkan jika tidak ingin mengubah cover</small>
            <br><br>

            <label for="slug">Slug</label><br>
            <input type="text" class="form-control" value="{{$book->slug}}" name="slug" placeholder="enter-a-slug" />
            <br>

            <label for="description">Description</label> <br>
            <textarea name="description" id="description" class="form-control">{{$book->description}}</textarea>
            <br>

            <label for="categories">Categories</label>
            <select multiple class="form-control" name=" categories[]" id="categories">
                @foreach($book->categories as $category)
                <option value="{{$category->id}}" @if($category->id)
                    selected
                    @endif>
                    {{$category->name}}
                </option>
                @endforeach
            </select>
            <br>
            <br>

            <label for="stock">Stock</label><br>
            <input type="text" class="form-control" placeholder="Stock" id="stock" name="stock"
                value="{{$book->stock}}">
            <br>

            <label for="author">Author</label>
            <input placeholder="Author" value="{{$book->author}}" type="text" id="author" name="author"
                class="form-control">
            <br>

            <label for="publisher">Publisher</label><br>
            <input class="form-control" type="text" placeholder="Publisher" name="publisher" id="publisher"
                value="{{$book->publisher}}">
            <br>

            <label for="price">Price</label><br>
            <input type="text" class="form-control" name="price" placeholder="Price" id="price"
                value="{{$book->price}}">
            <br>

            <label for="">Status</label>
            <select name="status" id="status" class="form-control">
                <option {{$book->status == 'PUBLISH' ? 'selected' : ''}} value="PUBLISH">PUBLISH</option>
                <option {{$book->status == 'DRAFT' ? 'selected' : ''}} value="DRAFT">DRAFT</option>
            </select>
            <br>

            <button class="btn btn-primary" value="PUBLISH">Update</button>

        </form>
    </div>
</div>

@endsection

@section('footer-scripts')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
$('#categories').select2({

    ajax: {
        // instead of writing the function to execute the request we use Select2's convenient helper
        url: 'http://127.0.0.1:8000/ajax/categories/search',
        dataType: 'json',
        data: function(params) {
            return {
                term: params.name
            }
        },
        processResults: function(data) {
            return {
                results: data.map(function(item) {
                    return {
                        id: item.id,
                        text: item.name
                    }
                })
            }
        },
    },

});
var categories = $("$book->categories");

categories.forEach(function(category) {
    var option = new Option(category.name, category.id, true, true);
    $('#categories').append(option).trigger('change');
});
</script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.global')

@section('title') Daftar Buku @endsection

@section('content')
@if(session('status'))
<div class="alert alert-success">
    {{session('status')}}
</div>
@endif
<div class="row">
    <!-- FITUR CARI -->
    <div class="col-md-6">

        <form action="{{route('books.index')}}">

            <div class="input-group">
                <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control"
                    placeholder="Cari berdasarkan judul buku ... ">
                <div class="input-group-append">
                    <input type="submit" value="Filter" class="btn btn-primary">
                </div>
            </div>

        </form>
    </div>

    <!-- 
    ? 'active' : => menampilkan link mana yang sedang aktif,
    sehingga akan seperti button ketika di klik
-->
    <!-- all menu's-->
    <!-- <div class="col-md-6"> -->
    <div class="col-md-6">

        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">

                <a class="nav-link {{Request::get('status') == NULL && Request::path() == 'books' ? 'active' : ''}}"
                    href="{{route('books.index')}}">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::get('status') == 'publish' ? 'active' : '' }}"
                    href="{{route('books.index', ['status' => 'publish'])}}">Publish</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::get('status') == 'draft' ? 'active' : '' }}"
                    href="{{route('books.index', ['status' => 'draft'])}}">Draft</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::path() == 'books/trash' ? 'active' : ''}}"
                    href="{{route('books.trash')}}">Trash</a>
            </li>
        </ul>
    </div>
</div>
<hr class="my-3">
<div class="row">

    <div class="col-md-12 text-left">
        <a href="{{route('books.create')}}" class="btn btn-primary">+ Tambah Buku</a>

    </div>
</div>
<br>

<!-- DAFTAR BUKU -->

<table class="table table-bordered table-stripped">
    <thead>
        <tr>
            <th><b>Cover</b></th>
            <th><b>Title</b></th>
            <th><b>Author</b></th>
            <th><b>Status</b></th>
            <th><b>Categories</b></th>
            <th><b>Stock</b></th>
            <th><b>Price</b></th>
            <th><b>Action</b></th>
        </tr>
    </thead>
    <tbody>
        @foreach($books as $book)
        <tr>
            <td>
                @if($book->cover)
                <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
                @endif
            </td>
            <td>{{$book->title}}</td>
            <td>{{$book->author}}</td>
            <td>
                @if($book->status == "DRAFT")
                <span class="badge bg-dark text-white">{{$book->status}}</span>
                @else
                <span class="badge badge-success">{{$book->status}}</span>
                @endif
            </td>
            <td>
                <ul class="pl-3">
                    @foreach($book->categories as $category)
                    <li>{{$category->name}}</li>
                    @endforeach
                </ul>
            </td>
            <td>{{$book->stock}}</td>
            <td>{{$book->price}}</td>
            <td>
                <!-- EDIT -->
                <a href="{{route('books.edit', [$book->id])}}" class="btn btn-info btn-sm"> Edit </a>
                <!-- DELETE -->
                <form method="POST" class="d-inline" onsubmit="return confirm('Move book to trash?')"
                    action="{{route('books.destroy', [$book->id])}}">

                    @csrf
                    <input type="hidden" value="DELETE" name="_method">

                    <input type="submit" value="Trash" class="btn btn-danger btn-sm">

                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan="10">
                {{$books->appends(Request::all())->links()}}
            </td>
        </tr>
    </tfoot>
</table>

@endsection

resources/views/books/trash.blade.php
@extends('layouts.global')

@section('title') Trashed Books @endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif
        <div class="row">
            <!-- FITUR CARI -->
            <div class="col-md-6">

                <form action="{{route('books.index')}}">

                    <div class="input-group">
                        <input name="keyword" type="text" value="{{Request::get('keyword')}}" class="form-control"
                            placeholder="Filter by title">
                        <div class="input-group-append">
                            <input type="submit" value="Filter" class="btn btn-primary">
                        </div>
                    </div>

                </form>
            </div>

            <!-- 
    ? 'active' : => menampilkan link mana yang sedang aktif,
    sehingga akan seperti button ketika di klik
-->
            <!-- all menu's-->
            <!-- <div class="col-md-6"> -->
            <div class="col-md-6">

                <ul class="nav nav-pills card-header-pills">
                    <li class="nav-item">

                        <a class="nav-link {{Request::get('status') == NULL && Request::path() == 'books' ? 'active' : ''}}"
                            href="{{route('books.index')}}">All</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{Request::get('status') == 'publish' ? 'active' : '' }}"
                            href="{{route('books.index', ['status' => 'publish'])}}">Publish</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{Request::get('status') == 'draft' ? 'active' : '' }}"
                            href="{{route('books.index', ['status' => 'draft'])}}">Draft</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{Request::path() == 'books/trash' ? 'active' : ''}}"
                            href="{{route('books.trash')}}">Trash</a>
                    </li>
                </ul>
            </div>
        </div>

        <hr class="my-3">


        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th><b>Cover</b></th>
                    <th><b>Title</b></th>
                    <th><b>Author</b></th>
                    <th><b>Categories</b></th>
                    <th><b>Stock</b></th>
                    <th><b>Price</b></th>
                    <th><b>Action</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach($books as $book)
                <tr>
                    <td>
                        @if($book->cover)
                        <img src="{{asset('storage/' . $book->cover)}}" width="96px" />
                        @endif
                    </td>
                    <td>{{$book->title}}</td>
                    <td>{{$book->author}}</td>
                    <td>
                        <ul class="pl-3">
                            @foreach($book->categories as $category)
                            <li>{{$category->name}}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{$book->stock}}</td>
                    <td>{{$book->price}}</td>
                    <td>
                        <!-- RESTORE -->
                        <form method="POST" action="{{route('books.restore', [$book->id])}}" class="d-inline">

                            @csrf

                            <input type="submit" value="Restore" class="btn btn-success btn-sm" />
                        </form>
                        <!-- PERMANENT DELETE -->
                        <form method="POST" action="{{route('books.delete-permanent', [$book->id])}}" class="d-inline"
                            onsubmit="return confirm('Delete this book permanently?')">

                            @csrf
                            <input type="hidden" name="_method" value="DELETE">

                            <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="10">
                        {{$books->appends(Request::all())->links()}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection