routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
|--------------------------------------------------------------------------
| Trash , Restore, Permanent Delete
|--------------------------------------------------------------------------
|
| Selalu letakkan 3 controller tersebut di atas resource method
| karena full memakai CRUD resource maka menggunakan ::resource
|
*/

Route::get('/', function(){
    return view('auth.login');
});
 /*
|--------------------------------------------------------------------------
| AUTH
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");
Auth::routes();//login

Route::match(["GET", "POST"], "/register", function(){
    return redirect("/login");
})->name("register");

Route::get('/home', 'HomeController@index')->name('home');
 /*
|--------------------------------------------------------------------------
| USERS
|--------------------------------------------------------------------------
*/

Route::resource('/users',"UserController");//karena full memakai resource

/*
|--------------------------------------------------------------------------
| CATEGORY
|--------------------------------------------------------------------------
*/

 Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');

 Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');

 Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');



Route::resource('/categories', 'CategoryController');
/*
|--------------------------------------------------------------------------
| BOOKS
|--------------------------------------------------------------------------
*/

Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');

Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');

Route::get('/books/trash', 'BookController@trash')->name('books.trash');

Route::resource('/books', 'BookController');
Route::get('/ajax/categories/search', 'CategoryController@ajaxSearch'); // fitur pencarian buku menggunakan ajax
/*
|--------------------------------------------------------------------------
| ORDERS
|--------------------------------------------------------------------------
*/
Route::resource('orders', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function books()
    {
        return $this->belongsToMany('App\Book')->withPivot('quantity');
    }
    // dynamic property di model Order 
    public function getTotalQuantityAttribute()
    {
        $total_quantity = 0;

        foreach($this->books as $book){
            $total_quantity += $book->pivot->quantity; 
            // menjumlahkan quantity yang diambil dari tabel pivot, 
            // hasil penjumlahan tersebut yang akan menjadi nilai dari dynamic property
        }

        return $total_quantity;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class OrderController extends Controller
{
    public function __construct()
    {
        // OTORISASI GATE
        $this->middleware(function($request, $next)
        {
            if(Gate::allows('manage-orders')) return $next($request);
            abort(403, 'Oops!Anda tidak memiliki hak akses kesini');
          });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->get('status');
        $buyer_email = $request->get('buyer_email');
        // menangkap request filter dari form yang di tambahkan di halaman list order
        $orders = Order::with('user')
                ->with('books')
                // whereHas ini untuk mencari order berdasarkan dari email pembeli 
                ->whereHas('user', function($query) use ($buyer_email) 
                {
                    $query->where('email', 'LIKE', "%$buyer_email%");
                })
                // dan melakukan filtering di halaman daftar order berdasarkan status dan email pembeli
                ->where('status', 'LIKE', "%$status%")
                ->paginate(10);

        return view('orders.index', ['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::findOrFail($id);

        return view('orders.edit', ['order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);

        $order->status = $request->get('status');
      
        $order->save();
      
        return redirect()->route('orders.index', [$order->id])->with('status', 'Order status succesfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/edit.blade.php
@extends('layouts.global')

@section('title') Edit order @endsection

@section('content')

<div class="row">
    <div class="col-md-8">
        @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
        @endif

        <form class="shadow-sm bg-white p-3" action="{{route('orders.update', [$order->id])}}" method="POST">

            @csrf

            <input type="hidden" name="_method" value="PUT">

            <label for="invoice_number">Invoice number</label><br>
            <input type="text" class="form-control" value="{{$order->invoice_number}}" disabled>
            <br>

            <label for="">Buyer</label><br>
            <input disabled class="form-control" type="text" value="{{$order->user->name}}">
            <br>

            <label for="created_at">Order date</label><br>
            <input type="text" class="form-control" value="{{$order->created_at}}" disabled>
            <br>

            <label for="">Books ({{$order->totalQuantity}}) </label><br>
            <ul>
                @foreach($order->books as $book)
                <li>{{$book->title}} <b>({{$book->pivot->quantity}})</b></li>
                @endforeach
            </ul>

            <label for="">Total price</label><br>
            <input class="form-control" type="text" value="{{$order->total_price}}" disabled>
            <br>

            <label for="status">Status</label><br>
            <select class="form-control" name="status" id="status">
                <option {{$order->status == "SUBMIT" ? "selected" : ""}} value="SUBMIT">SUBMIT</option>
                <option {{$order->status == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
                <option {{$order->status == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
                <option {{$order->status == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
            </select>
            <br>

            <input type="submit" class="btn btn-primary" value="Update">

        </form>
    </div>
</div>

@endsection

resources/views/orders/index.blade.php
@extends('layouts.global')

@section('title') Orders list @endsection

@section('content')
<form action="{{route('orders.index')}}">
    <div class="row">
        <div class="col-md-5">
            <input value="{{Request::get('buyer_email')}}" name="buyer_email" type="text" class="form-control"
                placeholder="Cari pembeli berdasarkan email..">
        </div>
        <div class="col-md-2">
            <select name="status" class="form-control" id="status">
                <option value="">ANY</option>
                <option {{Request::get('status') == "SUBMIT" ? "selected" : ""}} value="SUBMIT">SUBMIT</option>
                <option {{Request::get('status') == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
                <option {{Request::get('status') == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
                <option {{Request::get('status') == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
            </select>
        </div>
        <div class="col-md-2">
            <input type="submit" value="Filter" class="btn btn-primary">
        </div>
    </div>
</form>

<hr class="my-3">
<div class="row">
    <div class="col-md-12">
        <table class="table table-stripped table-bordered">
            <thead>
                <tr>
                    <th>Invoice number</th>
                    <th><b>Status</b></th>
                    <th><b>Buyer</b></th>
                    <th><b>Total quantity</b></th>
                    <th><b>Order date</b></th>
                    <th><b>Total price</b></th>
                    <th><b>Actions</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $order)
                <tr>
                    <td>{{$order->invoice_number}}</td>
                    <td>
                        @if($order->status == "SUBMIT")
                        <span class="badge bg-warning text-light">{{$order->status}}</span>
                        @elseif($order->status == "PROCESS")
                        <span class="badge bg-info text-light">{{$order->status}}</span>
                        @elseif($order->status == "FINISH")
                        <span class="badge bg-success text-light">{{$order->status}}</span>
                        @elseif($order->status == "CANCEL")
                        <span class="badge bg-dark text-light">{{$order->status}}</span>
                        @endif
                    </td>
                    <td>
                        {{$order->user->name}} <br>
                        <small>{{$order->user->email}}</small>
                    </td>
                    <td>{{$order->totalQuantity}} pc (s)</td>
                    <td>{{$order->created_at}}</td>
                    <td>{{$order->total_price}}</td>
                    <td>
                        <!-- EDIT -->
                        <a href="{{route('orders.edit', [$order->id])}}" class="btn btn-info btn-sm"> Edit</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="10">
                        {{$orders->appends(Request::all())->links()}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection